import { test, expect } from '@playwright/test'
import { snapshot, target } from './fixtures.mjs'
import { openFixture, view, observations } from './support'

test('linked actor views filter one context; global activity and native message filters remain explicit',async({page,request})=>{
  const data=snapshot()
  data.envelopes.push({id:'worker-progress',sender:target.actor,recipient:'/operator',type:'PROGRESS',payload:'Only selected worker progress',ordinal:'9',version:'1'})
  await openFixture(page,request,{snapshot:data})
  await page.getByRole('link',{name:`Open chat with ${target.actor}, waiting`,exact:true}).click()
  const actorURL=new URL(page.url())
  expect(actorURL.searchParams.get('run')).toBe(target.run)
  expect(actorURL.pathname).toBe('/chat/root/worker')
  expect(actorURL.searchParams.get('incarnation')).toBe(target.incarnation)
  await view(page,'Timeline')
  const timeline=page.getByRole('table',{name:'Conversation activity timeline'})
  await expect(timeline).toContainText('request-worker-0')
  await expect(timeline).not.toContainText('request-root-0')
  await page.getByRole('checkbox',{name:'Global activity',exact:true}).check()
  await expect(timeline).toContainText('request-root-0')
  await page.getByRole('checkbox',{name:'Global activity',exact:true}).uncheck()
  await view(page,'Inbox')
  const inbox=page.getByRole('list',{name:'Inbox messages'})
  await expect(inbox).toContainText('Fixture status for /root/worker')
  await expect(inbox.getByRole('listitem')).toHaveCount(2)
  await page.getByRole('combobox',{name:'Message type',exact:true}).selectOption('PROGRESS')
  await expect(inbox.getByRole('listitem')).toHaveCount(1)
  await expect(inbox).toContainText('Only selected worker progress')
  expect(new URL(page.url()).searchParams.get('type')).toBe('PROGRESS')
  await page.reload()
  await expect(inbox.getByRole('listitem')).toHaveCount(1)
  await view(page,'Chat')
  await expect(page.getByRole('complementary',{name:'Workers'}).getByRole('link',{name:target.actor,exact:true})).toHaveAttribute('aria-current','page')
  expect((await observations(request)).commands).toHaveLength(0)
})

test('conversation selection grants no actor control and preserves unrelated URL parameters',async({page,request})=>{
  await openFixture(page,request)
  await page.goto('/timeline?conversation=worker&operator-note=keep-me')
  const selected=new URL(page.url())
  expect(selected.searchParams.get('conversation')).toBe('worker')
  expect(selected.searchParams.get('actor')).toBeNull()
  expect(selected.searchParams.get('operator-note')).toBe('keep-me')
  await view(page,'Timeline')
  await expect(page.getByRole('table',{name:'Conversation activity timeline'})).toContainText('request-worker-0')
  await expect(page.getByRole('table',{name:'Conversation activity timeline'})).not.toContainText('request-root-0')
  await view(page,'Chat')
  await expect(page.getByLabel('Message to selected actor',{exact:true})).toBeDisabled()
  await expect(page.getByRole('button',{name:'Send input',exact:true})).toBeDisabled()
  expect(new URL(page.url()).searchParams.get('operator-note')).toBe('keep-me')
  expect((await observations(request)).commands).toHaveLength(0)
})

test('workflow actor with no model conversation has an exact inspection and control path',async({page,request})=>{
  const data=snapshot()
  const identity={...target,actor:'/root/workflow',incarnation:'workflow-only'}
  data.actors.push({identity,parent:data.actors[0].identity,kind:'workflow',lifecycle:'waiting',modelConversation:null as any,activeRound:'00000000-0000-4000-8000-000000000001'})
  await openFixture(page,request,{snapshot:data})
  await page.getByRole('link',{name:`Open actor page for workflow actor ${identity.actor}, waiting`,exact:true}).click()
  await view(page,'Timeline')
  await expect(page.getByText('request-root-0',{exact:false})).toHaveCount(0)
  await view(page,'Chat')
  await expect(page.getByRole('complementary',{name:'Workers'}).getByRole('link',{name:identity.actor,exact:true})).toHaveAttribute('aria-current','page')
  await expect(page.getByLabel('Message to selected actor',{exact:true})).toBeEnabled()
  expect((await observations(request)).commands).toHaveLength(0)
})
