manifest_path = "Cargo.toml"
third_party_dir = "."
precise_srcs = true
vendor = false

[buck]
buildscript_genrule = "tidepool_buildscript_run"
buckfile_imports = """
load(\"//build/rust:buildscript.bzl\", \"tidepool_buildscript_run\")
load(\"@prelude//rust:cargo_package.bzl\", \"cargo\")
rust_library = cargo.rust_library
rust_binary = cargo.rust_binary
"""
