import { afterEach, describe, expect, it, vi } from 'vitest'
import { act, fireEvent, render, screen, waitFor } from '@testing-library/react'
import NodeWindow from './NodeWindow'

const hash = 'a'.repeat(64)
const page = (requestId = 'request-1', offset = 0, count = 1, nextOffset: number | null = null, text = 'text') => ({
  requestId, parentId: 'parent-1', branch: '/root',
  items: Array.from({ length: count }, (_, index) => ({ position: String(offset + index), hash, byteLen: '91',
    item: { type: 'message', role: 'assistant', content: `${text} ${offset + index}` } })),
  nextOffset: nextOffset === null ? null : String(nextOffset), oversizedItem: null,
})
const response = (value: unknown, status = 200) => new Response(JSON.stringify(value), { status })
function deferred() {
  let resolve!: (response: Response) => void
  let reject!: (error: Error) => void
  const promise = new Promise<Response>((yes, no) => { resolve = yes; reject = no })
  return { promise, resolve, reject }
}
const list = () => screen.getByRole('list', { name: 'Retained request items' })
const idle = async () => waitFor(() => expect(screen.getByRole('button', { name: 'Refresh history' })).toBeEnabled())

afterEach(() => vi.unstubAllGlobals())

describe('retained request inspection', () => {
  it('moves keyboard focus to the inspector heading when it opens', async () => {
    vi.stubGlobal('fetch', vi.fn().mockResolvedValue(response(page('request-1'))))
    render(<NodeWindow requestId="request-1" onClose={() => {}} />)
    await waitFor(() => expect(screen.getByRole('heading', { name: 'Request history · request-1' })).toHaveFocus())
  })

  it('replaces each 50-item page, returns through the previous-offset stack, and rereads the same offset', async () => {
    const fetchMock = vi.fn().mockResolvedValueOnce(response(page('request-1', 0, 50, 50)))
      .mockResolvedValueOnce(response(page('request-1', 50, 50, 100)))
      .mockResolvedValueOnce(response(page('request-1', 100, 1)))
      .mockResolvedValueOnce(response(page('request-1', 50, 50, 100)))
      .mockResolvedValueOnce(response(page('request-1', 0, 50, 50)))
    vi.stubGlobal('fetch', fetchMock)
    render(<NodeWindow requestId="request-1" onClose={() => {}} />)
    await idle()
    expect(screen.getAllByRole('listitem')).toHaveLength(50)
    expect(screen.getByRole('button', { name: 'Previous page' })).toBeDisabled()
    fireEvent.click(screen.getByRole('button', { name: 'Next page' }))
    await idle()
    expect(screen.getAllByRole('listitem')).toHaveLength(50)
    expect(list().textContent).toContain('text 50')
    expect(screen.queryByLabelText('Text item 0')).toBeNull()
    fireEvent.click(screen.getByRole('button', { name: 'Next page' }))
    await idle()
    expect(screen.getAllByRole('listitem')).toHaveLength(1)
    expect(screen.queryByRole('button', { name: 'Next page' })).toBeNull()
    fireEvent.click(screen.getByRole('button', { name: 'Previous page' }))
    await idle()
    expect(list().textContent).toContain('text 50')
    fireEvent.click(screen.getByRole('button', { name: 'Previous page' }))
    await idle()
    expect(screen.getByLabelText('Text item 0')).toBeInTheDocument()
    expect(fetchMock.mock.calls.map(([url]) => url)).toEqual([0, 50, 100, 50, 0].map((offset) => `/api/history/request-1?offset=${offset}&limit=50`))
  })

  it('requires explicit oversized skip even for a 413 empty page and preserves return offsets', async () => {
    const blocked = { ...page('request-1', 50, 0), nextOffset: '50',
      oversizedItem: { position: '50', hash, byteLen: '270000', skipOffset: '51' } }
    const fetchMock = vi.fn().mockResolvedValueOnce(response(page('request-1', 0, 50, 50)))
      .mockResolvedValueOnce(response(blocked, 413)).mockResolvedValueOnce(response(page('request-1', 51)))
      .mockResolvedValueOnce(response(blocked, 413))
    vi.stubGlobal('fetch', fetchMock)
    render(<NodeWindow requestId="request-1" onClose={() => {}} />)
    await idle()
    fireEvent.click(screen.getByRole('button', { name: 'Next page' }))
    await idle()
    expect(fetchMock).toHaveBeenCalledTimes(2)
    expect(screen.queryAllByRole('listitem')).toHaveLength(0)
    expect(screen.getByText(/Full large-item retrieval is unavailable/)).toBeInTheDocument()
    expect(screen.queryByRole('button', { name: 'Next page' })).toBeNull()
    fireEvent.click(screen.getByRole('button', { name: 'Skip this item' }))
    await idle()
    expect(screen.getByLabelText('Text item 51')).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Previous page' }))
    await idle()
    expect(screen.getByRole('button', { name: 'Skip this item' })).toBeEnabled()
    expect(fetchMock.mock.calls.map(([url]) => url)).toEqual([0, 50, 51, 50].map((offset) => `/api/history/request-1?offset=${offset}&limit=50`))
  })

  it('keeps the complete mixed-page return path after a failed next-page read', async () => {
    const blocked = { ...page('request-1', 50, 0), nextOffset: '50',
      oversizedItem: { position: '50', hash, byteLen: '270000', skipOffset: '51' } }
    const fetchMock = vi.fn().mockResolvedValueOnce(response(page('request-1', 0, 50, 50)))
      .mockResolvedValueOnce(response(blocked, 413))
      .mockResolvedValueOnce(response(page('request-1', 51, 50, 101)))
      .mockResolvedValueOnce(response({}, 503))
      .mockResolvedValueOnce(response(page('request-1', 101, 1)))
      .mockResolvedValueOnce(response(page('request-1', 51, 50, 101)))
      .mockResolvedValueOnce(response(blocked, 413))
      .mockResolvedValueOnce(response(page('request-1', 0, 50, 50)))
    vi.stubGlobal('fetch', fetchMock)
    render(<NodeWindow requestId="request-1" onClose={() => {}} />)
    await idle()

    fireEvent.click(screen.getByRole('button', { name: 'Next page' }))
    await idle()
    fireEvent.click(screen.getByRole('button', { name: 'Skip this item' }))
    await idle()
    expect(screen.getByLabelText('Text item 51')).toBeInTheDocument()

    fireEvent.click(screen.getByRole('button', { name: 'Next page' }))
    await idle()
    expect(screen.getByRole('alert').textContent).toContain('unavailable')
    expect(screen.getByLabelText('Text item 51')).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Retry history' }))
    await idle()
    expect(screen.getByLabelText('Text item 101')).toBeInTheDocument()

    fireEvent.click(screen.getByRole('button', { name: 'Previous page' }))
    await idle()
    expect(screen.getByLabelText('Text item 51')).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Previous page' }))
    await idle()
    expect(screen.getByRole('button', { name: 'Skip this item' })).toBeEnabled()
    fireEvent.click(screen.getByRole('button', { name: 'Previous page' }))
    await idle()
    expect(screen.getByLabelText('Text item 0')).toBeInTheDocument()
    expect(fetchMock.mock.calls.map(([url]) => url)).toEqual([0, 50, 51, 101, 101, 51, 50, 0]
      .map((offset) => `/api/history/request-1?offset=${offset}&limit=50`))
  })

  it('offers first-load Retry and keeps a loaded page through failed next/refresh reads', async () => {
    const fetchMock = vi.fn().mockResolvedValueOnce(response({}, 503))
      .mockResolvedValueOnce(response(page('request-1', 0, 1, 1)))
      .mockRejectedValueOnce(new Error('network lost'))
      .mockResolvedValueOnce(response(page('request-1', 1)))
      .mockResolvedValueOnce(response({}, 503))
      .mockResolvedValueOnce(response(page('request-1', 1, 1, null, 'fresh')))
    vi.stubGlobal('fetch', fetchMock)
    render(<NodeWindow requestId="request-1" onClose={() => {}} />)
    await idle()
    expect(screen.getByRole('alert').textContent).toContain('unavailable')
    fireEvent.click(screen.getByRole('button', { name: 'Retry history' }))
    await idle()
    fireEvent.click(screen.getByRole('button', { name: 'Next page' }))
    await idle()
    expect(screen.getByRole('alert').textContent).toContain('network lost')
    expect(screen.getByLabelText('Text item 0')).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Retry history' }))
    await idle()
    expect(screen.getByLabelText('Text item 1')).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Refresh history' }))
    await idle()
    expect(screen.getByLabelText('Text item 1')).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Retry history' }))
    await idle()
    expect(list().textContent).toContain('fresh 1')
    expect(fetchMock.mock.calls.map(([url]) => url)).toEqual([0, 0, 1, 1, 1, 1].map((offset) => `/api/history/request-1?offset=${offset}&limit=50`))
  })

  it('aborts old selection and ignores reverse completion after A -> B -> A', async () => {
    const first = deferred(), second = deferred(), third = deferred()
    const fetchMock = vi.fn().mockReturnValueOnce(first.promise).mockReturnValueOnce(second.promise).mockReturnValueOnce(third.promise)
    vi.stubGlobal('fetch', fetchMock)
    const { rerender } = render(<NodeWindow requestId="A" onClose={() => {}} />)
    rerender(<NodeWindow requestId="B" onClose={() => {}} />)
    expect(fetchMock.mock.calls[0]?.[1].signal.aborted).toBe(true)
    rerender(<NodeWindow requestId="A" onClose={() => {}} />)
    expect(fetchMock.mock.calls[1]?.[1].signal.aborted).toBe(true)
    await act(async () => third.resolve(response(page('A', 0, 1, null, 'new A'))))
    await idle()
    await act(async () => second.resolve(response(page('B', 0, 1, null, 'old B'))))
    await act(async () => first.resolve(response(page('A', 0, 1, null, 'old A'))))
    expect(list().textContent).toContain('new A')
    expect(list().textContent).not.toContain('old A')
    expect(list().textContent).not.toContain('old B')
  })

  it('resets the same request ID in a new host/conversation and rejects stale failures/auth transitions', async () => {
    const old = deferred(), replacement = deferred()
    const auth = vi.fn()
    const fetchMock = vi.fn().mockResolvedValueOnce(response(page('same', 0, 1, 1)))
      .mockReturnValueOnce(old.promise).mockReturnValueOnce(replacement.promise)
    vi.stubGlobal('fetch', fetchMock)
    const { rerender } = render(<NodeWindow requestId="same" hostRun="host1" conversationId="c1" onAuthExpired={auth} onClose={() => {}} />)
    await idle()
    fireEvent.click(screen.getByRole('button', { name: 'Next page' }))
    rerender(<NodeWindow requestId="same" hostRun="host2" conversationId="c2" onAuthExpired={auth} onClose={() => {}} />)
    expect(fetchMock.mock.calls[1]?.[1].signal.aborted).toBe(true)
    expect(screen.queryAllByRole('listitem')).toHaveLength(0)
    await act(async () => replacement.resolve(response(page('same', 0, 1, null, 'new host'))))
    await idle()
    await act(async () => old.resolve(response({}, 401)))
    expect(auth).not.toHaveBeenCalled()
    expect(screen.queryByRole('alert')).toBeNull()
    expect(list().textContent).toContain('new host')
    expect(fetchMock.mock.calls[2]?.[0]).toBe('/api/history/same?offset=0&limit=50')
  })

  it('refreshes only on the passed durable signature and retains current paging through callback rerenders', async () => {
    const fetchMock = vi.fn().mockResolvedValueOnce(response(page('request-1', 0, 1, 1)))
      .mockResolvedValueOnce(response(page('request-1', 1)))
      .mockResolvedValueOnce(response(page('request-1', 1, 1, null, 'durable')))
    vi.stubGlobal('fetch', fetchMock)
    const { rerender } = render(<NodeWindow requestId="request-1" refreshKey="v1" onClose={() => {}} />)
    await idle()
    fireEvent.click(screen.getByRole('button', { name: 'Next page' }))
    await idle()
    rerender(<NodeWindow requestId="request-1" refreshKey="v1" onClose={() => {}} onAuthExpired={() => {}} />)
    expect(fetchMock).toHaveBeenCalledTimes(2)
    rerender(<NodeWindow requestId="request-1" refreshKey="v2" onClose={() => {}} />)
    await idle()
    expect(fetchMock.mock.calls[2]?.[0]).toContain('offset=1&limit=50')
    expect(list().textContent).toContain('durable')
  })

  it('supersedes a pending refresh without letting old failures clear the fresh page', async () => {
    const old = deferred(), fresh = deferred()
    const fetchMock = vi.fn().mockResolvedValueOnce(response(page()))
      .mockReturnValueOnce(old.promise).mockReturnValueOnce(fresh.promise)
    vi.stubGlobal('fetch', fetchMock)
    const { rerender } = render(<NodeWindow requestId="request-1" refreshKey="v1" onClose={() => {}} />)
    await idle()
    fireEvent.click(screen.getByRole('button', { name: 'Refresh history' }))
    rerender(<NodeWindow requestId="request-1" refreshKey="v2" onClose={() => {}} />)
    expect(fetchMock.mock.calls[1]?.[1].signal.aborted).toBe(true)
    await act(async () => fresh.resolve(response(page('request-1', 0, 1, null, 'fresh'))))
    await idle()
    await act(async () => old.reject(new Error('stale failure')))
    expect(list().textContent).toContain('fresh')
    expect(screen.queryByRole('alert')).toBeNull()
  })

  it('reports current confirmed auth refusal and aborts outstanding reads on unmount', async () => {
    const pending = deferred(), auth = vi.fn()
    const fetchMock = vi.fn().mockResolvedValueOnce(response({}, 403)).mockReturnValueOnce(pending.promise)
    vi.stubGlobal('fetch', fetchMock)
    const { unmount } = render(<NodeWindow requestId="request-1" onAuthExpired={auth} onClose={() => {}} />)
    await idle()
    expect(auth).toHaveBeenCalledTimes(1)
    fireEvent.click(screen.getByRole('button', { name: 'Retry history' }))
    unmount()
    expect(fetchMock.mock.calls[1]?.[1].signal.aborted).toBe(true)
    await act(async () => pending.resolve(response({}, 401)))
    expect(auth).toHaveBeenCalledTimes(1)
  })

  it('rejects a response for another request instead of displaying its data', async () => {
    vi.stubGlobal('fetch', vi.fn().mockResolvedValue(response(page('another-request'))))
    render(<NodeWindow requestId="request-1" onClose={() => {}} />)
    await idle()
    expect(screen.getByRole('alert').textContent).toContain('invalid page')
    expect(screen.queryAllByRole('listitem')).toHaveLength(0)
  })

  it('retries the failed navigation offset but Refresh rereads the visible page and preserves its previous stack', async () => {
    const fetchMock = vi.fn().mockResolvedValueOnce(response(page('request-1', 0, 50, 50)))
      .mockResolvedValueOnce(response({}, 503))
      .mockResolvedValueOnce(response({}, 503))
      .mockResolvedValueOnce(response(page('request-1', 0, 50, 50, 'refreshed')))
      .mockResolvedValueOnce(response(page('request-1', 50, 1)))
      .mockResolvedValueOnce(response(page('request-1', 0, 50, 50)))
    vi.stubGlobal('fetch', fetchMock)
    render(<NodeWindow requestId="request-1" onClose={() => {}} />)
    await idle()
    fireEvent.click(screen.getByRole('button', { name: 'Next page' }))
    await idle()
    expect(screen.getByLabelText('Text item 0')).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Retry history' }))
    await idle()
    fireEvent.click(screen.getByRole('button', { name: 'Refresh history' }))
    await idle()
    expect(list().textContent).toContain('refreshed 0')
    expect(screen.getByRole('button', { name: 'Previous page' })).toBeDisabled()
    fireEvent.click(screen.getByRole('button', { name: 'Next page' }))
    await idle()
    fireEvent.click(screen.getByRole('button', { name: 'Previous page' }))
    await idle()
    expect(screen.getByRole('button', { name: 'Previous page' })).toBeDisabled()
    expect(fetchMock.mock.calls.map(([url]) => url)).toEqual([0, 50, 50, 0, 50, 0].map((offset) => `/api/history/request-1?offset=${offset}&limit=50`))
  })

  it('automatically refreshes the visible offset after a failed next-page navigation', async () => {
    const fetchMock = vi.fn().mockResolvedValueOnce(response(page('request-1', 0, 50, 50)))
      .mockResolvedValueOnce(response({}, 503))
      .mockResolvedValueOnce(response(page('request-1', 0, 50, 50, 'durable')))
    vi.stubGlobal('fetch', fetchMock)
    const { rerender } = render(<NodeWindow requestId="request-1" refreshKey="v1" onClose={() => {}} />)
    await idle()
    fireEvent.click(screen.getByRole('button', { name: 'Next page' }))
    await idle()
    rerender(<NodeWindow requestId="request-1" refreshKey="v2" onClose={() => {}} />)
    await idle()
    expect(list().textContent).toContain('durable 0')
    expect(screen.getByRole('button', { name: 'Previous page' })).toBeDisabled()
    expect(fetchMock.mock.calls.map(([url]) => url)).toEqual([0, 50, 0].map((offset) => `/api/history/request-1?offset=${offset}&limit=50`))
  })

  it('offers local Retry after timeout without expiring authentication and clears the old read', async () => {
    vi.useFakeTimers()
    const auth = vi.fn(), old = deferred()
    const fetchMock = vi.fn().mockReturnValueOnce(old.promise)
      .mockResolvedValueOnce(response(page()))
    vi.stubGlobal('fetch', fetchMock)
    try {
      render(<NodeWindow requestId="request-1" onAuthExpired={auth} onClose={() => {}} />)
      await act(async () => vi.advanceTimersByTimeAsync(10_000))
      expect(screen.getByRole('alert').textContent).toContain('timed out')
      expect(auth).not.toHaveBeenCalled()
      expect(fetchMock.mock.calls[0]?.[1].signal.aborted).toBe(true)
      await act(async () => fireEvent.click(screen.getByRole('button', { name: 'Retry history' })))
      expect(screen.getByLabelText('Text item 0')).toBeInTheDocument()
      expect(screen.queryByRole('alert')).toBeNull()
      expect(vi.getTimerCount()).toBe(0)
      await act(async () => old.resolve(response({}, 401)))
      expect(auth).not.toHaveBeenCalled()
      expect(screen.getByLabelText('Text item 0')).toBeInTheDocument()
      expect(screen.queryByRole('alert')).toBeNull()
    } finally {
      vi.useRealTimers()
    }
  })

  it('preserves the nonzero visible page previous stack when Refresh replaces a failed navigation', async () => {
    const fetchMock = vi.fn().mockResolvedValueOnce(response(page('request-1', 0, 50, 50)))
      .mockResolvedValueOnce(response(page('request-1', 50, 50, 100)))
      .mockResolvedValueOnce(response({}, 503))
      .mockResolvedValueOnce(response(page('request-1', 50, 50, 100, 'refreshed')))
      .mockResolvedValueOnce(response(page('request-1', 0, 50, 50)))
    vi.stubGlobal('fetch', fetchMock)
    render(<NodeWindow requestId="request-1" onClose={() => {}} />)
    await idle()
    fireEvent.click(screen.getByRole('button', { name: 'Next page' }))
    await idle()
    fireEvent.click(screen.getByRole('button', { name: 'Next page' }))
    await idle()
    fireEvent.click(screen.getByRole('button', { name: 'Refresh history' }))
    await idle()
    expect(list().textContent).toContain('refreshed 50')
    fireEvent.click(screen.getByRole('button', { name: 'Previous page' }))
    await idle()
    expect(screen.getByLabelText('Text item 0')).toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'Previous page' })).toBeDisabled()
    expect(fetchMock.mock.calls.map(([url]) => url)).toEqual([0, 50, 100, 50, 0].map((offset) => `/api/history/request-1?offset=${offset}&limit=50`))
  })
})
